# WiFi Mixin
# Adds WiFi Station (Client) connectivity to any device
# Requires wifi_ssid and wifi_password secrets
# Use this mixin to add pre-provisioned WiFi credentials to your device

substitutions:
  # WiFi credentials (override in instances if needed)
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true
