# ESP32 DevKit V1 Board Preset
# Generic ESP32-WROOM-32D development board
# Provides standardized GPIO pin mappings

esp32:
  board: esp32dev
  framework:
    type: esp-idf

substitutions:
  # Standard I2C pins (easily customizable in instances)
  pin_i2c_sda: GPIO21
  pin_i2c_scl: GPIO22
  
  # Standard UART pins
  pin_uart_tx: GPIO17
  pin_uart_rx: GPIO16
  
  # Status LED
  pin_status_led: GPIO2
  
  # Extra GPIO slots for future use
  pin_extra_1: GPIO23
  pin_extra_2: GPIO19
